fix wrong text
techhtml/reactjs.org pull request #6
Opened 2017-12-30 18:17 UTC by devJang

2017-12-30 22:11 UTC, techhtml requested changes

2017-12-30 22:11 UTC, techhtml commented on content/docs/static-type-checking.md
> +먼저 터미널에서 프로젝트 디렉토리로 이동합니다. 그리고 두 커드를 실행합니다.
오타났습니다

2017-12-31 05:22 UTC, devJang commented on content/docs/static-type-checking.md
> +먼저 터미널에서 프로젝트 디렉토리로 이동합니다. 그리고 두 커드를 실행합니다.
오..주의해서 풀리퀘 하겠습니다.

2017-12-31 05:36 UTC, techhtml approved these changes

2017-12-31 05:36 UTC, merged